title: Neslihan Kalayci
description: Personal portfolio and blog of Neslihan Kalayci - Developer, Innovator, Problem Solver
remote_theme: just-the-docs/just-the-docs

url: https://nkalayci.github.io

author: Neslihan Kalayci
email: neslihan@example.com

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
